version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor:
      name: python/default
      tag: "3.11"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
          environment:
            SQLALCHEMY_DATABASE_URL: sqlite:///test.db
            SQLALCHEMY_DATABASE_URL_TEST: sqlite:///test.db
            JWT_SECRET_KEY: "a-dummy-jwt-key-just-for-testing-purposes"
            JWT_ALGORITHM: "HS256"
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
