version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.2
      - image: redis:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Start Redis
          command: |
            redis-server &
            sleep 10
      - run:
          name: Run tests
          command: python -m pytest
          environment:
            SQLALCHEMY_DATABASE_URL: sqlite:///test.db
            SQLALCHEMY_DATABASE_URL_TEST: sqlite:///test.db
            JWT_SECRET_KEY: "a-dummy-jwt-key-just-for-testing-purposes"
            JWT_ALGORITHM: "HS256"
            JWT_EXPIRE_TIME_IN_MINUTES: 1440
            JWT_REFRESH_EXPIRE_TIME_IN_MINUTES: 7200
            REDIS_HOST: "127.0.0.1"
            REDIS_PORT: 6379

workflows:
  test_my_app:
    jobs:
      - build_and_test
