version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          version: "3.11"
      - run:
          name: Run tests
          command: python -m pytest
          environment:
            SQLALCHEMY_DATABASE_URL: sqlite:///test.db
            SQLALCHEMY_DATABASE_URL_TEST: sqlite:///test.db
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
